name: Update

on:
  push:
  schedule:
    - cron: 0 23 * * * 

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update
      run: |
       # 央视源
       # rm -f CCTV.m3u && wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CCTV.m3u
        rm -f CCTV.m3u && wget https://telegram-feiyangdigital.v1.mk/bestv.m3u -O CCTV.m3u
        sed -i -n '/央视/,+1p' CCTV.m3u
        sed -i '1i #EXTM3U' CCTV.m3u
        sed -i '/^\s*$/d' CCTV.m3u
        # 卫视源
       # rm -f CNTV.m3u && wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV.m3u
        rm -f CNTV.m3u && wget https://telegram-feiyangdigital.v1.mk/bestv.m3u -O CNTV.m3u
        sed -i '/央视/,+1d' CNTV.m3u
        sed -i '/^\s*$/d' CNTV.m3u
        # 整合源
        rm -f IPTV.m3u && touch IPTV.m3u
        cat CCTV.m3u >> IPTV.m3u
        cat CNTV.m3u >> IPTV.m3u
        sed -i '/#EXTM3U/d' IPTV.m3u
        sed -i '1i #EXTM3U' IPTV.m3u
        sed -i '/^\s*$/d' IPTV.m3u
        # 节目单
        rm -f epg.xml && wget https://epg.112114.xyz/pp.xml -O epg.xml
        #  rm -f EPG.xml && wget http://epg.51zmt.top:8000/e.xml -O EPG.xml
        # 更新
        echo Last Update: `date +"%Y-%m-%d %H:%M:%S"` UTC > README.md
        git config --global user.name yk1n0rt
        git config --global user.email yk1n0rt@gmail.com
        git checkout --orphan latest_branc
        git add -A
        git commit -am "Update"
        git branch -D main
        git branch -m main
        git push -f origin main
